- hosts: all
  become: true
  vars:
    epel_repo: false
    update: false
    allinone: true
    custom_repo: 
      - "http://trunk.rdoproject.org/centos7-newton/current-passed-ci/delorean.repo"
      - "http://trunk.rdoproject.org/centos7-newton/delorean-deps.repo"
    packstack_add_options: "--os-swift-install=n"
  roles:
  - base
  - rdo
